name: shared_models
description: Shared models for vehicle applications
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.3
  json: ^0.20.4
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.8.4
  image_picker: ^1.0.7
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
