name: shared_models
description: Shared models for vehicle applications
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  date_format: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cloud_firestore: ^5.6.3
  intl: ^0.18.1